FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema si son necesarias (útil para la compilación de ciertos paquetes)
RUN apt-get update && apt-get install -y build-essential

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8000
EXPOSE 8501

# CMD por defecto (será sobrescrito por docker-compose.yml)
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]