from abc import ABC, abstractmethod
from typing import List, Optional
from src.domain.models import Client, Pet, Appointment, MedicalRecord, Invoice, Feedback

class IClientRepository(ABC):
    @abstractmethod
    async def create(self, client: Client) -> str: ...
    @abstractmethod
    async def get_all(self) -> List[Client]: ...
    @abstractmethod
    async def get_by_id(self, client_id: str) -> Optional[Client]: ...

class IPetRepository(ABC):
    @abstractmethod
    async def create(self, pet: Pet) -> str: ...
    @abstractmethod
    async def list_by_owner(self, owner_id: str) -> List[Pet]: ...
    @abstractmethod
    async def get_by_id(self, pet_id: str) -> Optional[Pet]: ...

class IAppointmentRepository(ABC):
    @abstractmethod
    async def create(self, appointment: Appointment) -> str: ...
    @abstractmethod
    async def list_by_pet(self, pet_id: str) -> List[Appointment]: ...
    @abstractmethod
    async def update_status(self, appointment_id: str, status: str) -> bool: ...

class IMedicalRepository(ABC):
    @abstractmethod
    async def add_entry(self, entry: MedicalRecord) -> str: ...
    @abstractmethod
    async def get_history(self, pet_id: str) -> List[MedicalRecord]: ...

class IBillingRepository(ABC):
    @abstractmethod
    async def create_invoice(self, invoice: Invoice) -> str: ...
    @abstractmethod
    async def get_client_invoices(self, client_id: str) -> List[Invoice]: ...

class IFeedbackRepository(ABC):
    @abstractmethod
    async def add_feedback(self, feedback: Feedback) -> str: ...